version: '3'

services:
  backend:
    container_name: django
    build:
      context: .
      dockerfile: ./django/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./django/code:/app
    depends_on: 
      - db

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment: 
      MYSQL_DATABASE: api
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes: 
      - ./dbdata:/var/lib/mysql
    ports: 
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=user
      - PMA_PASSWORD=password
    ports:
      - 8080:80
    depends_on: 
      - db

  front:
    build:
      context: .
      dockerfile: ./react/Dockerfile
    container_name: react
    restart: always
    volumes:
      - ./react/code:/usr/src/app
    command: sh -c "yarn start"
    ports:
      - "3000:3000"